CREATE TABLE student (id PRIMARY KEY, name TEXT, grade INTEGER);
INSERT INTO student (id,name,grade) VALUES (1510,"Jordan",9);
INSERT INTO student (id,name,grade) VALUES (1689,"Gabriel",9);
INSERT INTO student (id,name,grade) VALUES (1381,"Tiffany",9);
INSERT INTO student (id,name,grade) VALUES (1709,"Cassandra",9);
INSERT INTO student (id,name,grade) VALUES (1101,"Haley",10);
INSERT INTO student (id,name,grade) VALUES (1782,"Andrew",10);
INSERT INTO student (id,name,grade) VALUES (1468,"Kris",10);
INSERT INTO student (id,name,grade) VALUES (1641,"Brittany",10);
INSERT INTO student (id,name,grade) VALUES (1247,"Alexis",11);
INSERT INTO student (id,name,grade) VALUES (1316,"Austin",11);
INSERT INTO student (id,name,grade) VALUES (1911,"Gabriel",11);
INSERT INTO student (id,name,grade) VALUES (1501,"Jessica",11);
INSERT INTO student (id,name,grade) VALUES (1304,"Jordan",12);
INSERT INTO student (id,name,grade) VALUES (1025,"John",12);
INSERT INTO student (id,name,grade) VALUES (1934,"Kyle",12);
INSERT INTO student (id,name,grade) VALUES (1661,"Logan",12);
